// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo83b7jylboMZqIVdH5Q0BezKS31r0kFA',
    appId: '1:396223871595:web:c4034a0c5cc76a92980f2e',
    messagingSenderId: '396223871595',
    projectId: 'cartease-95696',
    authDomain: 'cartease-95696.firebaseapp.com',
    storageBucket: 'cartease-95696.firebasestorage.app',
    measurementId: 'G-8LYNZXZ3PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo83b7jylboMZqIVdH5Q0BezKS31r0kFA',
    appId: '1:396223871595:android:a8e983256b65b414980f2e',
    messagingSenderId: '396223871595',
    projectId: 'cartease-95696',
    storageBucket: 'cartease-95696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV7fu-hDHwIgB5Hm6CPXS-pXvI6xSrD-4',
    appId: '1:396223871595:ios:828b09d6c17d2b43980f2e',
    messagingSenderId: '396223871595',
    projectId: 'cartease-95696',
    storageBucket: 'cartease-95696.firebasestorage.app',
    iosBundleId: 'com.example.cartease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV7fu-hDHwIgB5Hm6CPXS-pXvI6xSrD-4',
    appId: '1:396223871595:ios:828b09d6c17d2b43980f2e',
    messagingSenderId: '396223871595',
    projectId: 'cartease-95696',
    storageBucket: 'cartease-95696.firebasestorage.app',
    iosBundleId: 'com.example.cartease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo83b7jylboMZqIVdH5Q0BezKS31r0kFA',
    appId: '1:396223871595:android:a8e983256b65b414980f2e',
    messagingSenderId: '396223871595',
    projectId: 'cartease-95696',
    storageBucket: 'cartease-95696.firebasestorage.app',
  );
}
